### ISSUE TITLE
Buildings at the Output of the csv report

### ISSUE THREAD

**Issue by LAAP** [CityScope/CSL_Energy#1]
The output of the csv report doesn't show all the buildings (only shows one)

**Comment by agrignard** [comment]
Fix in the following commit 
https://github.com/CityScope/CSL_Andorra_Energy/commit/0bdc0914e475e6b83fe913fe9077ed68fa253792

As mention in the GAMA library example (e.g Save Statement/Save to CSV.gaml line 18) the facet rewrite need to be set to false in order not to rewrite the file.

In yout ase the facet was equal to true (value by default) so every time a building was saving its status it would overwrite the file, that why at the end you only had one building in the file (the last one)
