### ISSUE TITLE
Java error: NoClassDefFoundError

### ISSUE THREAD

**Issue by LAAP** [CityScope/CSL_Energy#4]
Hi, a "Java error: NoClassDefFoundError" Has been occurred when running the model
<img width="1680" alt="captura de pantalla 2018-09-24 a las 12 53 46" src="https://user-images.githubusercontent.com/19315213/45966593-88578880-bff9-11e8-97f9-eaa3df77786a.png">

**Comment by agrignard** [comment]
sorry for that. I temporally removed the kml export (in the last commit)  that for now only work on the eclipse version of GAMA and not the RC2 (see gama-platform/gama#2543)

The model should now work
